version: '3.4'

services:
  memcached:
    image: 'bitnami/memcached:latest'
    restart: always
    networks:
      - openaprs-net
  openaprs:
    build: .
    restart: always
    platform: linux/amd64
    networks:
      - openaprs-net
    env_file:
      - env
    volumes:
      - ./data/openstomp/etc:/root/openstomp/etc
      - ./data/openstomp/logs:/root/openstomp/logs
      - ./data/aprsinject/etc:/root/aprsinject/etc
      - ./data/aprsinject/logs:/root/aprsinject/logs
      - ./data/aprspruner/etc:/root/aprspruner/etc
      - ./data/aprspruner/logs:/root/aprspruner/logs
      - ./data/aprsfeed/etc:/root/aprsfeed/etc
      - ./data/aprsfeed/logs:/root/aprsfeed/logs
      - ./data/aprsfeed/bursts:/root/aprsfeed/bursts
    depends_on:
      - memcached
#  proxy:
#    build: proxy
#    ports:
#      - 80:80
#    depends_on: 
#      - backend
volumes:
  db-data:
networks:
  openaprs-net:
    external: true
